---
title: Grandpa Scarer
hero_image: images/banner.png
description: Make a box to drop a toy spider on Grandpa's head
original_url: https://raspberrypi.org/learning/grandpa-scarer
theme: red
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 4, design-3, programming-3, phys-comp-2, manufacture-4, community-0
interests: humour, big-project
technologies: electronic-components, python
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Making the box enclosure
- title: Using a servo
- title: Wiring up the button
- title: Playing sounds
- title: Assembly
- title: Code
  completion: internal
- title: Scare a grandpa
- title: What next?
